name: Run PHPCS
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Install dependencies
      run: composer install --dev --prefer-dist --no-progress --no-suggest
    - name: File Changes Action
      id: get_file_changes
      uses: trilom/file-changes-action@v1.2.4
      with:
        githubToken: ${{ secrets.GH_BOT_TOKEN }}
        output: '" "'
    - name: PHPCS check
      run: ./vendor/bin/phpcs "${{ steps.get_file_changes.outputs.files }}" --report=checkstyle
