name: Upload pack as Release Asset
on:
  release:
    types: [created]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Set git to use CRLF
        run: |
          git config --global core.autocrlf true
          git config --global core.eol crlf
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Pack as zip
        run:  git archive -o zblogphp.zip HEAD
      - name: Put AppCentre Plugin
        run: |
          php ./utils/put_appcentre.php
          zip -g zblogphp.zip zb_users/plugin/AppCentre/* zb_users/plugin/AppCentre/**/*
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./zblogphp.zip
          asset_name: zblogphp.zip
          asset_content_type: application/zip
